### ISSUE TITLE
Node.js equivalent?

### ISSUE THREAD

**Issue by edwardrose946** [coryasilva/squrll#1]
Hi Cory, 

I've been digging around looking for a node.js library that takes a querystring with $filter params to turn into a SQL expression and your repo came up. It looks great! Did you base this project on a similar project or know of any equivalent projects in other languages?

Kind regards,

Edward

**Comment by coryasilva** [comment]
Hi Edward,
Thanks! I really did not find anything out there. But, rewriting the [parser](https://github.com/coryasilva/squrll/blob/master/models/Parser.cfc) in javascript should be a fairly quick task.  I would suggest adopting [knex.js](https://knexjs.org/) for parts of the [Composer](https://github.com/coryasilva/squrll/blob/master/models/Composer.cfc) file. 

I am not sure of your use case but in nodejs, nowadays, I just add this filters adhoc in an openapi spec document and use knexjs to build the query, it is pretty fast to develop.

```
https://my.api/v1/resources
  ?filter[a][eq]=1
  &filter[b][ilike]=%blah%
  &sort=-a,+b
```

The stack that has worked well for me is:

express-openapi - request and response validator
express - api framework
knex - query builder
helmet - security headers
lightship - health check

**Comment by edwardrose946** [comment]
Thanks for the response :)

Yeah I couldn't find anything out the box either. I'm currently working on a serverless app, querying S3 buckets with S3 Select. Quick parsing and ad hoc building of the SQL expression is probably going to be good enough. Thanks for the knex recommendation!
